/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVenuesRouteImport } from './routes/_admin/venues'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminConcertsRouteImport } from './routes/_admin/concerts'
import { Route as AdminBookingsRouteImport } from './routes/_admin/bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminFinanceSalesReportRouteImport } from './routes/_admin/finance/sales-report'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConcertsRoute = AdminConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFinanceSalesReportRoute = AdminFinanceSalesReportRouteImport.update({
  id: '/finance/sales-report',
  path: '/finance/sales-report',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/bookings': typeof AdminBookingsRoute
  '/concerts': typeof AdminConcertsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/venues': typeof AdminVenuesRoute
  '/finance/sales-report': typeof AdminFinanceSalesReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/bookings': typeof AdminBookingsRoute
  '/concerts': typeof AdminConcertsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/venues': typeof AdminVenuesRoute
  '/finance/sales-report': typeof AdminFinanceSalesReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/concerts': typeof AdminConcertsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/venues': typeof AdminVenuesRoute
  '/_admin/finance/sales-report': typeof AdminFinanceSalesReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/bookings'
    | '/concerts'
    | '/dashboard'
    | '/venues'
    | '/finance/sales-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/bookings'
    | '/concerts'
    | '/dashboard'
    | '/venues'
    | '/finance/sales-report'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/analytics'
    | '/_admin/bookings'
    | '/_admin/concerts'
    | '/_admin/dashboard'
    | '/_admin/venues'
    | '/_admin/finance/sales-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/venues': {
      id: '/_admin/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/concerts': {
      id: '/_admin/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof AdminConcertsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/finance/sales-report': {
      id: '/_admin/finance/sales-report'
      path: '/finance/sales-report'
      fullPath: '/finance/sales-report'
      preLoaderRoute: typeof AdminFinanceSalesReportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminConcertsRoute: typeof AdminConcertsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
  AdminFinanceSalesReportRoute: typeof AdminFinanceSalesReportRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminConcertsRoute: AdminConcertsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminVenuesRoute: AdminVenuesRoute,
  AdminFinanceSalesReportRoute: AdminFinanceSalesReportRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
