/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminVenuesRouteImport } from './routes/_admin/venues'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminConcertsRouteImport } from './routes/_admin/concerts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVenuesRoute = AdminVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConcertsRoute = AdminConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/concerts': typeof AdminConcertsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/venues': typeof AdminVenuesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/concerts': typeof AdminConcertsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/venues': typeof AdminVenuesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/concerts': typeof AdminConcertsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/venues': typeof AdminVenuesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/concerts' | '/dashboard' | '/venues'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/concerts' | '/dashboard' | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/concerts'
    | '/_admin/dashboard'
    | '/_admin/venues'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/venues': {
      id: '/_admin/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof AdminVenuesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/concerts': {
      id: '/_admin/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof AdminConcertsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminConcertsRoute: typeof AdminConcertsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminVenuesRoute: typeof AdminVenuesRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminConcertsRoute: AdminConcertsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminVenuesRoute: AdminVenuesRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
